### ISSUE TITLE
Not parallel

### ISSUE THREAD

**Issue by wbv** [kaliRegenold/rust#1]
This isn't parallel

**Comment by ceritelli** [comment]
This issues is a non-issues because it is an issue. We will look into this issues so that this non-issue can be analysed and become a solved non-issue. Thank you for your time and consideration.

**Comment by wbv** [comment]
![kalireact](https://user-images.githubusercontent.com/7481569/47795101-78f9e800-dce7-11e8-9ce4-a8e8415e9cc7.png)
